name: fcs
description: Application to quickly switch Flutter channels, without downloading and upgrading everytime
version: 0.1.0
homepage: https://github.com/MohiuddinM/fcs

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  args: ^1.6.0
  quick_log: ^2.0.0
  dio: ^3.0.10

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
