name: fcs
description: Application to quickly switch Flutter channels, without downloading and upgrading everytime
version: 0.2.1
homepage: https://github.com/MohiuddinM/fcs

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path: ^1.8.0-nullsafety.3
  quick_log: ^4.0.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
